### PR TITLE
Adding check for codePrintHTML, allows to run without modifications on OpenBD

### PR DESCRIPTION
**Pull request by MFernstrom**
With the check you don't have to make any modifications to run MXUnit on OpenBD.

### CODE REVIEW

**Comment by MFernstrom** [comment]
Anybody home? Is this officially abandonware?

**Comment by bdw429s** [comment]
All the other MXUnit users I know have moved to TestBox (which supports MXUnit tests for easy conversion). I think @denuno might be the only person still poking at this repo, so maybe try reaching out to him?

**Comment by MFernstrom** [comment]
I can't remember what but there was some issue with running TestBox on OpenBD.

MXUnit runs with this tiny change, so it's a simple fix.

@denuno would you mind accepting a couple of small changes to the repo?

**Comment by denuno** [comment]
Thank you!

**Comment by MFernstrom** [comment]
Awesome, thanks @denuno.

**Pull request merged**
